fail-on-severity: "low"
allow-licenses:
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "MIT"
  - "Apache-2.0"
  - "ISC"
  - "BlueOak-1.0.0"
  - "0BSD"
  - "Python-2.0"
  - "MIT-CMU" # Pillow's license
  - "CC-BY-NC-4.0"
  - "GPL-1.0-or-later"
  - "LGPL-2.0-or-later"
  - "LicenseRef-scancode-proprietary-license"
fail-on-scopes:
  - "runtime"
  - "development"
  - "unknown"
license-check: true
vulnerability-check: true
allow-dependencies-licenses:
  - "pkg:npm/thingies" # Docs site (dependency of dependency)
