import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  genaiDocsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      description: 'Getting started guide for OpenVINO GenAI',
      items: [
        'getting-started/introduction',
        {
          type: 'link',
          label: 'Installation',
          href: 'https://docs.openvino.ai/2025/get-started/install-openvino.html?PACKAGE=OPENVINO_GENAI&VERSION=v_2025_0_0&OP_SYSTEM=WINDOWS&DISTRIBUTION=PIP',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: '.',
      customProps: {
        // Exclude duplicated autogenerated category (docs/getting-started/_category_.json) as "Getting Started" is defined manually above
        excludeCategories: ['Getting Started'],
      },
    },
  ],
};

export default sidebars;
