# ----------------------------------------------------------------------
# GLOBAL CONFIGURATION
# ----------------------------------------------------------------------
global_context:
  model_type: "qwen2_5_vl"

# ----------------------------------------------------------------------
# MODULES DEFINITION
# ----------------------------------------------------------------------
pipeline_modules:

  # --- 0. Parameter Module ---
  pipeline_params:
    type: "ParameterModule"
    outputs:
      - name: "image"
        type: "OVTensor"
      - name: "prompt"
        type: "String"

  # --- 1. Image Preprocessing Module ---
  image_preprocessor:           # Module Name
    type: "ImagePreprocessModule"
    device: "GPU"
    description: "Image or Video preprocessing."
    inputs:
      - name: "image"           # single image
        type: "OVTensor"        # Support DataType: [OVTensor, OVRemoteTensor]
        source: "pipeline_params.image"
    outputs:
      - name: "raw_data"        # Output port name
        type: "OVTensor"        # Support DataType: [OVTensor, OVRemoteTensor]
      - name: "source_size"     # Output port name
        type: "VecInt"          # Support DataType: [VecInt]
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"

  # --- 2. Prompt Encode Module ---
  prompt_encoder:
    type: "TextEncoderModule"
    device: "GPU"
    inputs:
      - name: "prompt"
        type: "String"
        source: "pipeline_params.prompt"
      - name: "encoded_image"
        type: "OVTensor"
        source: "image_preprocessor.raw_data"
      - name: "source_size"
        type: "VecInt"
        source: "image_preprocessor.source_size"
    outputs:
      - name: "input_ids"
        type: "OVTensor"
      - name: "mask"
        type: "OVTensor"
      - name: "images_sequence"
        type: "VecInt"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"

  # --- 3. Prompt Embedding Module ---
  text_embedding:
    type: "TextEmbeddingModule"
    device: "GPU"
    inputs:
      - name: "input_ids"
        type: "OVTensor"
        source: "prompt_encoder.input_ids"
    outputs:
      - name: "input_embedding"
        type: "OVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"
      scale_emb: "1.0"
  
  # --- 4. Vision Encoder Module ---
  vision_encoder:
    type: "VisionEncoderModule"
    device: "GPU"
    inputs:
      - name: "preprocessed_image"
        type: "OVTensor"
        source: "image_preprocessor.raw_data"
      - name: "source_size"
        type: "VecInt"
        source: "image_preprocessor.source_size"
      - name: "images_sequence"
        type: "VecInt"
        source: "prompt_encoder.images_sequence"
      - name: "input_ids"
        type: "OVTensor"
        source: "prompt_encoder.input_ids"
    outputs:
      - name: "image_embedding"
        type: "OVTensor"
      - name: "video_embedding"
        type: "OVTensor"
      - name: "position_ids"
        type: "OVTensor"
      - name: "rope_delta"
        type: "Int"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"
      vision_start_token_id: 151652

  # --- 5. Embedding Merger Module ---
  embedding_merger:
    type: "EmbeddingMergerModule"
    device: "GPU"
    inputs:
      - name: "input_ids"
        type: "OVTensor"
        source: "prompt_encoder.input_ids"
      - name: "input_embedding"
        type: "OVTensor"
        source: "text_embedding.input_embedding"
      - name: "image_embedding"
        type: "OVTensor"
        source: "vision_encoder.image_embedding"
      - name: "video_embedding"
        type: "OVTensor"
        source: "vision_encoder.video_embedding"
    outputs:
      - name: "merged_embedding"
        type: "OVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"

  # --- 6. LLM Inference Module ---
  llm_inference:
    type: "LLMInferenceModule"
    description: "LLM module for Continuous Batch pipeline"
    device: "GPU"
    inputs:
      - name: "embeds"
        type: "OVTensor"
        source: "embedding_merger.merged_embedding"
      - name: "position_ids"
        type: "OVTensor"
        source: "vision_encoder.position_ids"
      - name: "rope_delta"
        type: "Int"
        source: "vision_encoder.rope_delta"
    outputs:
      - name: "generated_text"
        type: "String"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen2.5-VL-3B-Instruct/INT4/"
      max_new_tokens: "16"
      do_sample: "false"
      top_p: "1.0"
      top_k: "50"
      temperature: "1.0"
      repetition_penalty: "1.0"
  
  # --- 7. Result Module ---
  pipeline_result:
    type: "ResultModule"
    description: "Collects final results and formats the output structure."
    inputs:
      - name: "generated_text"
        type: "String"
        source: "llm_inference.generated_text"