name: SDL tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/**'

permissions: read-all

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-linux-sdl
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  sdl_tests:
    name: SDL tests
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone sources and tests
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python tests dependencies
        run: |
          python3 -m pip install flake8 pytest black bandit

      - name: Lint with flake8 (WWB)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --config=./setup.cfg
        working-directory: ${{ github.workspace }}/tools/who_what_benchmark

      - name: Lint with flake8 (LLM)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --config=./setup.cfg
        working-directory: ${{ github.workspace }}/tools/llm_bench

      - name: Bandit tests
        run: python -m bandit --recursive --configfile bandit.yml .

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@aeb13962e8044961d8758c86772280caa8f179ee # v0.34.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          version: v0.69.2

      - name: Dependency Review
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          config-file: './.github/dependency_review.yml'
