name: Windows (VS 2022, Python 3.11)
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - 'releases/**'

permissions: read-all # Required by https://github.com/ossf/scorecard/blob/e23b8ad91fd6a64a0a971ca4fc0a4d1650725615/docs/checks.md#token-permissions

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-windows
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  OV_BRANCH: 'master'
  OV_TARBALL: ''

jobs:
  openvino_download:
    name: Download OpenVINO package
    outputs:
      status: ${{ steps.openvino_download.outcome }}
      ov_artifact_name: ${{ steps.openvino_download.outputs.ov_artifact_name }}
      ov_wheel_source: ${{ steps.openvino_download.outputs.ov_wheel_source }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-2-cores-8gb
    container:
      image: 'openvinogithubactions.azurecr.io/openvino_provider:0.1.0'
      volumes:
        - /mount:/mount
        - ${{ github.workspace }}:${{ github.workspace }}
    continue-on-error: true

    steps:
      - id: openvino_download
        uses: openvinotoolkit/openvino/.github/actions/openvino_provider@master
        with:
          platform: windows
          commit_packages_to_provide: all
          revision: latest_available_commit

  genai_python_lib:
    name: OpenVINO genai extension (cmake + wheel)
    needs: [ openvino_download ]
    timeout-minutes: 90
    defaults:
      run:
        shell: pwsh
    runs-on: windows-2022

    env:
      OV_INSTALL_DIR: ${{ github.workspace }}\\ov
      CMAKE_BUILD_PARALLEL_LEVEL: null

    steps:
      - name: Clone openvino.genai
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Download OpenVINO package
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ needs.openvino_download.outputs.ov_artifact_name }}
          path: ${{ env.OV_INSTALL_DIR }}
          merge-multiple: true

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          toolset: 14.42 # v2022

      - name: Build genai libs
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build/
          cmake --build ./build/ --config Release --parallel --verbose
        env:
          CMAKE_TLS_VERIFY: 0

      - name: Test bindings
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install ./thirdparty/openvino_tokenizers/[transformers] -r ./tests/python_tests/requirements.txt --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pytest -v ./tests/python_tests/test_tokenizer.py::test_set_chat_template
        env:
          PYTHONPATH: "./build/" # cmd evaluates variables in a different way. Setting PYTHONPATH before setupvars.bat instead of doing that after solves that.

      - name: Test bindings (wheel)
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install . --verbose --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pip install ./tools/who_what_benchmark --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pytest -v ./tests/python_tests/ --ignore ./tests/python_tests/test_whisper_pipeline.py --ignore ./tests/python_tests/test_whisper_pipeline_static.py --ignore ./tests/python_tests/test_vlm_pipeline.py -k "not test_set_chat_template"

  genai_python_lib_whisper:
    name: OpenVINO genai extension whisper tests (cmake + wheel)
    needs: [ openvino_download ]
    timeout-minutes: 90
    defaults:
      run:
        shell: pwsh
    runs-on: windows-2022

    env:
      OV_INSTALL_DIR: ${{ github.workspace }}\\ov
      CMAKE_BUILD_PARALLEL_LEVEL: null

    steps:
      - name: Clone openvino.genai
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Download OpenVINO package
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ needs.openvino_download.outputs.ov_artifact_name }}
          path: ${{ env.OV_INSTALL_DIR }}
          merge-multiple: true

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          toolset: 14.42 # v2022

      - name: Build genai libs
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build/
          cmake --build ./build/ --config Release --target py_openvino_genai --parallel --verbose
        env:
          CMAKE_TLS_VERIFY: 0

      - name: Test bindings
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install ./thirdparty/openvino_tokenizers/[transformers] -r ./tests/python_tests/requirements.txt --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pytest -v ./tests/python_tests/test_whisper_pipeline.py -k test_smoke
        env:
          PYTHONPATH: "./build/" # cmd evaluates variables in a different way. Setting PYTHONPATH before setupvars.bat instead of doing that after solves that.

      - name: Test bindings (wheel)
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install . --verbose --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pip install ./tools/who_what_benchmark --find-links ${env:OV_INSTALL_DIR}/wheels
          
          # transformers 4.46.3 will enable return_timestamps tests
          # this check enabled for windows only. Ticket: 160205.
          python -m pip install transformers==4.46.3
          
          python -m pytest -v ./tests/python_tests/test_whisper_pipeline.py ./tests/python_tests/test_whisper_pipeline_static.py -k "not test_smoke"

  genai_python_lib_vlm:
    name: OpenVINO genai VLM tests (cmake + wheel)
    needs: [ openvino_download ]
    timeout-minutes: 90
    defaults:
      run:
        shell: pwsh
    runs-on: windows-2022-16-core

    env:
      OV_INSTALL_DIR: ${{ github.workspace }}\\ov
      CMAKE_BUILD_PARALLEL_LEVEL: null

    steps:
      - name: Clone openvino.genai
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Download OpenVINO package
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ needs.openvino_download.outputs.ov_artifact_name }}
          path: ${{ env.OV_INSTALL_DIR }}
          merge-multiple: true

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          toolset: 14.42 # v2022

      - name: Build genai libs
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build/
          cmake --build ./build/ --config Release --target py_openvino_genai --parallel --verbose
        env:
          CMAKE_TLS_VERIFY: 0

      - name: Test bindings
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install ./thirdparty/openvino_tokenizers/[transformers] -r ./tests/python_tests/requirements.txt --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pytest -v ./tests/python_tests/test_vlm_pipeline.py
        env:
          PYTHONPATH: "./build/" # cmd evaluates variables in a different way. Setting PYTHONPATH before setupvars.bat instead of doing that after solves that.

  genai_package:
    name: OpenVINO genai extension (install to OpenVINO package)
    strategy:
      matrix:
        build-type: [Release, Debug]
    needs: [ openvino_download ]
    timeout-minutes: 60
    defaults:
      run:
        shell: pwsh
    runs-on: windows-2022

    env:
      OV_INSTALL_DIR: ${{ github.workspace }}\\ov
      CMAKE_BUILD_PARALLEL_LEVEL: null

    steps:
      - name: Clone openvino.genai
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Download OpenVINO package
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ needs.openvino_download.outputs.ov_artifact_name }}
          path: ${{ env.OV_INSTALL_DIR }}
          merge-multiple: true

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          toolset: 14.42 # v2022

      - name: Build genai libs
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -S ./ -B ./build/
          cmake --build ./build/ --config ${{ matrix.build-type }} --target package -j
        env:
          CMAKE_TLS_VERIFY: 0

      - name: Build and Install dependencies
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python -m pip install ./thirdparty/openvino_tokenizers/[transformers] --find-links ${env:OV_INSTALL_DIR}/wheels
          python -m pip install -r ./samples/requirements.txt --find-links ${env:OV_INSTALL_DIR}/wheels
          optimum-cli export openvino --trust-remote-code --weight-format fp16 --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 TinyLlama-1.1B-Chat-v1.0
          optimum-cli export openvino --trust-remote-code --model openai/whisper-tiny whisper-tiny

      - name: Install samples
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake --install ./build/ --config ${{ matrix.build-type }} --prefix ${{ env.OV_INSTALL_DIR }}

      - name: Build samples (Release)
        if: ${{ 'Release' == matrix.build-type }} # build_samples enforces Release build
        run: |
          & ${{ env.OV_INSTALL_DIR }}\samples\cpp\build_samples.ps1 -i ${{ github.workspace }}/samples_install

      - name: Build samples (Debug)
        if: ${{ 'Release' != matrix.build-type }}
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE= -S ./ov/samples/cpp/ -B "samples build"
          cmake --build "samples build" --config ${{ matrix.build-type }} -j
          cmake --install "samples build" --config ${{ matrix.build-type }} --component samples_bin --prefix samples_install

      - name: Test C++ samples (greedy_causal_lm)
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          Start-Process -FilePath "${{ github.workspace }}/samples_install/samples_bin/greedy_causal_lm.exe" -ArgumentList "TinyLlama-1.1B-Chat-v1.0 ''"

      - name: Test C++ samples (whisper_speech_recognition)
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          curl -o how_are_you_doing_today.wav https://storage.openvinotoolkit.org/models_contrib/speech/2021.2/librispeech_s5/how_are_you_doing_today.wav
          Start-Process -FilePath "${{ github.workspace }}/samples_install/samples_bin/whisper_speech_recognition.exe" -ArgumentList "whisper-tiny how_are_you_doing_today.wav"

      - name: Test python samples (multinomial_causal_lm)
        if: ${{ 'Release' == matrix.build-type }} # Python bindings can be built in Release only
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python ${{ env.OV_INSTALL_DIR }}\samples\python\text_generation\multinomial_causal_lm.py TinyLlama-1.1B-Chat-v1.0 0

      - name: Test python samples (whisper_speech_recognition)
        if: ${{ 'Release' == matrix.build-type }} # Python bindings can be built in Release only
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          python ${{ env.OV_INSTALL_DIR }}\samples\python\whisper_speech_recognition\whisper_speech_recognition.py whisper-tiny how_are_you_doing_today.wav

  genai_build_nodejs_bindings:
    name: Build Node.js bindings
    needs: [ openvino_download ]
    timeout-minutes: 90
    defaults:
      run:
        shell: pwsh
    runs-on: windows-2022

    env:
      BUILD_DIR: ${{ github.workspace }}\\build
      INSTALL_DIR: ${{ github.workspace }}\\install
      OV_INSTALL_DIR: ${{ github.workspace }}\\ov
      CMAKE_BUILD_PARALLEL_LEVEL: null
      NODE_VERSION: 21

    steps:
      - name: Clone openvino.genai
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download OpenVINO package
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ needs.openvino_download.outputs.ov_artifact_name }}
          path: ${{ env.OV_INSTALL_DIR }}
          merge-multiple: true

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          toolset: 14.42 # v2022

      - name: Build GenAI Node.js bindings
        run: |
          . "${{ env.OV_INSTALL_DIR }}/setupvars.ps1"
          cmake -DCMAKE_BUILD_TYPE=Release `
            -DENABLE_JS=ON -DCPACK_GENERATOR=NPM `
            -DENABLE_PYTHON=OFF -DENABLE_WHEEL=OFF `
            -S ./ -B ${{ env.BUILD_DIR }}
          cmake --build ${{ env.BUILD_DIR }} --config Release --parallel --verbose
          cmake --install ${{ env.BUILD_DIR }} --config Release --prefix ${{ env.INSTALL_DIR }}

      - name: Pack Node.js bindings libs
        run: |
          $file=Get-ChildItem -Path "${{ env.INSTALL_DIR }}"
          $compress = @{
            Path = $file
            CompressionLevel = "Optimal"
            DestinationPath = "${{ env.BUILD_DIR }}/genai_nodejs_bindings.zip"
          }
          Compress-Archive @compress

      - name: Upload Archive Package with Node.js bindings
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: genai_nodejs_bindings
          path: ${{ env.BUILD_DIR }}/genai_nodejs_bindings.zip
          if-no-files-found: 'error'

      - name: Install npm package tests dependencies
        working-directory: ./src/js
        run: |
          Copy-Item -Recurse ${{ env.INSTALL_DIR }} bin
          npm install
          Remove-Item -Recurse -Force node_modules/openvino-node/bin
          Copy-Item -Recurse ${{ env.OV_INSTALL_DIR }}/openvino_js_package node_modules/openvino-node/bin

      - name: Run npm package tests
        working-directory: ./src/js
        run: |
          npm test

      - name: Install genai-node samples dependencies
        working-directory: ./samples/js/text_generation
        run: |
          npm install
          Remove-Item -Recurse -Force node_modules/openvino-node/bin
          Copy-Item -Recurse ${{ env.OV_INSTALL_DIR }}/openvino_js_package node_modules/openvino-node/bin

      - name: Run samples tests
        run: npm test
        env:
          MODEL_PATH: ./src/js/tests/models/Llama-3.1-8B-Instruct-FastDraft-150M-int8-ov
        working-directory: ./samples/js/text_generation

  Overall_Status:
    name: ci/gha_overall_status_windows
    needs: [openvino_download, genai_python_lib, genai_package, genai_python_lib_vlm, genai_python_lib_whisper]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs
        if: >-
          ${{
            contains(needs.*.result, 'failure') ||
            contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
